---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: batamqp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: batamqp
    spec:
      containers:
        -
          image: "batamqp:1.0"
          imagePullPolicy: Never
          name: batamqp
          ports:
            -
              containerPort: 8097
              name: http-port
