---
apiVersion: v1
kind: Service
metadata:
  name: codecoverageamqp
  namespace: default
spec:
  ports:
    - name: service
      port: 8098
      targetPort: 8098
      protocol: TCP
  selector:
    app: codecoverageamqp
  type: NodePort
