---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: complexdbamqp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: complexdbamqp
    spec:
      containers:
        -
          image: "complexdbamqp:1.0"
          imagePullPolicy: Never
          name: complexdbamqp
          ports:
            -
              containerPort: 8099
              name: http-port
