---
apiVersion: v1
kind: Service
metadata:
  name: complexdbamqp
  namespace: default
spec:
  ports:
    - name: service
      port: 8099
      targetPort: 8099
      protocol: TCP
  selector:
    app: complexdbamqp
  type: NodePort
