---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: findbugamqp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: findbugamqp
    spec:
      containers:
        -
          image: "findbugamqp:1.0"
          imagePullPolicy: Never
          name: findbugamqp
          ports:
            -
              containerPort: 8097
              name: http-port
