---
apiVersion: v1
kind: Service
metadata:
  name: findbugdbamqp
  namespace: default
spec:
  ports:
    - name: service
      port: 8097
      targetPort: 8097
      protocol: TCP
  selector:
    app: findbugdbamqp
  type: NodePort
