---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: locamqp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: locamqp
    spec:
      containers:
        -
          image: "locamqp:1.0"
          imagePullPolicy: Never
          name: locamqp
          ports:
            -
              containerPort: 8097
              name: http-port
