---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: locdbamqp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: locdbamqp
    spec:
      containers:
        -
          image: "locdbamqp:1.0"
          imagePullPolicy: Never
          name: locdbamqp
          ports:
            -
              containerPort: 8099
              name: http-port
