---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pmdamqp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: pmdamqp
    spec:
      containers:
        -
          image: "pmdamqp:1.0"
          imagePullPolicy: Never
          name: pmdamqp
          ports:
            -
              containerPort: 8097
              name: http-port
