---
apiVersion: v1
kind: Service
metadata:
  name: unitamqp
  namespace: default
spec:
  ports:
    - name: service
      port: 8097
      targetPort: 8097
      protocol: TCP
      nodePort: 32222
  selector:
    app: unitamqp
  type: NodePort
