---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: unitdbamqp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: unitdbamqp
    spec:
      containers:
        -
          image: "unitdbamqp:1.0"
          imagePullPolicy: Never
          name: unitdbamqp
          ports:
            -
              containerPort: 8099
              name: http-port
